routing:
    routes:
        - { method: 'GET', url: '/', callback: 'HomeController::index' }

        - { method: 'GET', url: '/home', callback: 'ToDoController::home', middleware: 'AuthOnlyMiddleware' }
        - { method: 'POST', url: '/add', callback: 'ToDoController::add', middleware: 'AuthOnlyMiddleware' }
        - { method: 'DELETE', url: '/delete', callback: 'ToDoController::delete', middleware: 'AuthOnlyMiddleware' }
        - { method: 'PUT', url: '/update', callback: 'ToDoController::update', middleware: 'AuthOnlyMiddleware' }
        - { method: 'PUT', url: '/complete', callback: 'ToDoController::complete', middleware: 'AuthOnlyMiddleware' }

        - { method: 'GET', url: '/login', callback: 'UserController::index' }
        - { method: 'POST', url: '/login', callback: 'UserController::login' }

        - { method: 'GET', url: '/test', callback: 'TestController::test' }
        - { method: 'GET', url: '/test2', callback: 'TestController::testSecond' }

    exceptions:
        - { exception: '\Greg\ToDo\Exceptions\Http\PageNotFoundException', callback: 'ErrorController::error404' }
        - { exception: '\Greg\ToDo\Exceptions\Http\PermissionDeniedException', callback: 'ErrorController::error403' }
        - { exception: '\Greg\ToDo\Exceptions\Http\BadRequestException', callback: 'ErrorController::error400' }
        - { exception: '\Exception', callback: 'ErrorController::error500', strict: true }