security:
    authentication:
        user_model: 'Greg\ToDo\Models\User'
        providers:
            post_request:
                class: '\Greg\ToDo\Authentication\Providers\PostRequestAuthenticationProvider'
                match:
                    method: 'POST'
                    url: '/login'
            session:
                class: '\Greg\ToDo\Authentication\Providers\SessionAuthenticationProvider'
                match:
                    method: 'ANY'
                    url: '*'
