services:
    application.database:
        class: 'Greg\ToDo\Database'
        singleton: true
        parameters:
            - {type: 'parameter', parameter: 'database_host'}
            - {type: 'parameter', parameter: 'database_port'}
            - {type: 'parameter', parameter: 'database_name'}
            - {type: 'parameter', parameter: 'database_user'}
            - {type: 'parameter', parameter: 'database_password'}

    repositories.todo_repository:
        class: 'Greg\ToDo\Repositories\ToDoRepository'
        parameters:
            - {type: 'service', service: 'application.database'}
