services:
    application.database:
        class: 'Greg\ToDo\Database'
        singleton: true
        parameters:
            - {type: 'config'}
            - {type: 'parameter', parameter: 'database_host'}
            - {type: 'parameter', parameter: 'database_port'}
            - {type: 'parameter', parameter: 'database_name'}
            - {type: 'parameter', parameter: 'database_user'}
            - {type: 'parameter', parameter: 'database_password'}

    application.file_handler:
        class: '\Greg\ToDo\FileHandler'
        parameters:
            - {type: 'config_item', config_item: 'application.upload_dir'}
            - {type: 'service', service: 'repositories.file_repository'}

    # database repositories
    repositories.todo_repository:
        class: '\Greg\ToDo\Repositories\ToDoRepository'
        parameters:
            - {type: 'service', service: 'application.database'}
    repositories.todo_comment_repository:
        class: '\Greg\ToDo\Repositories\ToDoCommentRepository'
        parameters:
            - {type: 'service', service: 'application.database'}
    repositories.user_repository:
        class: '\Greg\ToDo\Repositories\UserRepository'
        parameters:
            - {type: 'service', service: 'application.database'}
    repositories.usergroup_repository:
        class: '\Greg\ToDo\Repositories\UserGroupRepository'
        parameters:
            - {type: 'service', service: 'application.database'}
    repositories.file_repository:
        class: '\Greg\ToDo\Repositories\FileRepository'
        parameters:
            - {type: 'service', service: 'application.database'}
